channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==1.23.1
  - psutil==5.9.6
  - scikit-learn==1.3.2
  - scipy==1.10.1
name: mlflow-env
